data_dir: ~/workspace/check_interp/interpretability-bootcamp/reference_implementations/Intepretable-models/Tabular/datasets
data_file: US_130/diabetic_data.csv
framingham_file: framingham.csv #For train_framingham
support_file: support2.csv #For train_support
output_file: nam.pkl

train_params:
  hidden_units: [32,16,8] #framingham
  #hidden_units: [64, 32, 16]
  #num_epochs: 30
  num_epochs: 150 #framingham
  num_epochs: 50 #framingham_10year
  input_dim: 1 #framingham
  #batch_size: 256
  batch_size: 128 #framingham
  dropout_rate: 0.2
  l1_lambda: 0.02
  l2_lambda: 0.01
  patience: 10

optimizer:
  lr: 0.001
  weight_decay: 0.01

seed: 42
test_size: 0.2
pretrained: False
plot: True
